apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ghghhgghj
  description: hjhjh
  annotations: 
    github.com/project-slug: https://github.com/blamdemo/foobar2
    backstage.io/github-actions-id: https://github.com/blamdemo/foobar2
spec:
  type: service
  lifecycle: experimental
  owner: jhaals
